'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import type { SessionUser } from '@crm/contracts';
import { api } from '../../lib/api';
import { MobileNav } from '../components/mobile-nav';
import { AppNav } from '../components/app-nav';
type Dashboard={inventory:{products:number;units:number;lowStock:number;outStock:number;costValue?:string;saleValue:string;potentialProfit?:string};sales:{today:{count:number;revenue:string;profit?:string};week:{count:number;revenue:string};month:{count:number;revenue:string;profit?:string}};topProducts:Array<{name:string;sku:string;quantity:number;revenue:string}>;recentSales:Array<{id:string;number:string;totalAmount:string;confirmedAt:string;customer?:{firstName:string;lastName?:string};user:{displayName:string}}>;recentMovements:Array<{id:string;type:string;quantityDelta:number;occurredAt:string;variant:{sku:string;product:{name:string}};user:{displayName:string}}> ;trend:Array<{day:string;sales:number;revenue:string}>};
const money=(value?:string)=>value==null?'Oculto':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(Number(value));
export default function DashboardPage(){
 const router=useRouter();const[user,setUser]=useState<SessionUser|null>(null);const[data,setData]=useState<Dashboard|null>(null);const[error,setError]=useState('');
 useEffect(()=>{Promise.all([api<SessionUser>('/auth/me'),api<Dashboard>('/reports/dashboard')]).then(([session,dashboard])=>{setUser(session);setData(dashboard);}).catch((reason)=>{if(String(reason).includes('sesión'))router.replace('/login');else setError(reason instanceof Error?reason.message:'No se pudo cargar el panel.');});},[router]);
 if(!user||!data)return <main className="loading-screen">{error||'Calculando indicadores…'}</main>;
 const max=Math.max(...data.trend.map((item)=>Number(item.revenue)),1);
 return <main className="app-shell"><AppNav active="/dashboard"/><section className="workspace dashboard-workspace">
  <header><div><p className="eyebrow dark">PANEL GENERAL</p><h1>Buen día, {user.displayName}</h1><p className="muted">Resumen actualizado del negocio y el inventario.</p></div><div className="status"><i/> Datos en vivo</div></header>
  <section className="metric-grid"><article><span>Ventas de hoy</span><strong>{money(data.sales.today.revenue)}</strong><small>{data.sales.today.count} operaciones · Ganancia {money(data.sales.today.profit)}</small></article><article><span>Ventas del mes</span><strong>{money(data.sales.month.revenue)}</strong><small>{data.sales.month.count} operaciones · Ganancia {money(data.sales.month.profit)}</small></article><article><span>Unidades disponibles</span><strong>{data.inventory.units.toLocaleString('es-AR')}</strong><small>{data.inventory.products} productos registrados</small></article><article className={data.inventory.lowStock+data.inventory.outStock?'metric-alert':''}><span>Alertas de stock</span><strong>{data.inventory.lowStock+data.inventory.outStock}</strong><small>{data.inventory.lowStock} bajo mínimo · {data.inventory.outStock} agotadas</small></article></section>
  <section className="dashboard-grid"><article className="table-card chart-card"><div className="table-title"><div><p className="eyebrow dark">ÚLTIMOS 7 DÍAS</p><h2>Ritmo de ventas</h2></div><strong>{money(data.sales.week.revenue)}</strong></div><div className="bar-chart">{data.trend.map((item)=><div key={item.day} title={money(item.revenue)}><span style={{height:`${Math.max(6,Number(item.revenue)/max*100)}%`}}/><small>{new Date(item.day).toLocaleDateString('es-AR',{weekday:'short'})}</small></div>)}</div></article><article className="table-card inventory-value"><p className="eyebrow dark">VALOR DEL INVENTARIO</p><h2>{money(data.inventory.saleValue)}</h2><dl><div><dt>A costo</dt><dd>{money(data.inventory.costValue)}</dd></div><div><dt>Ganancia potencial</dt><dd>{money(data.inventory.potentialProfit)}</dd></div></dl></article></section>
  <section className="dashboard-grid lower"><article className="table-card"><div className="table-title"><h2>Más vendidos del mes</h2><span>Por unidades netas</span></div><div className="rank-list">{data.topProducts.length?data.topProducts.map((item,index)=><div key={item.sku}><b>{index+1}</b><span><strong>{item.name}</strong><small>{item.sku}</small></span><span><strong>{item.quantity} u.</strong><small>{money(item.revenue)}</small></span></div>):<p className="muted">Todavía no hay ventas este mes.</p>}</div></article><article className="table-card"><div className="table-title"><h2>Últimas ventas</h2><a href="/sales">Ver todas</a></div><div className="activity-list">{data.recentSales.map((sale)=><div key={sale.id}><span><strong>Venta #{sale.number}</strong><small>{sale.customer?`${sale.customer.firstName} ${sale.customer.lastName??''}`:'Consumidor final'} · {sale.user.displayName}</small></span><span><strong>{money(sale.totalAmount)}</strong><small>{new Date(sale.confirmedAt).toLocaleString('es-AR')}</small></span></div>)}</div></article></section>
  <article className="table-card"><div className="table-title"><h2>Movimientos recientes</h2><a href="/inventory">Abrir stock</a></div><div className="activity-list compact">{data.recentMovements.map((movement)=><div key={movement.id}><span><strong>{movement.variant.product.name}</strong><small>{movement.variant.sku} · {movement.type} · {movement.user.displayName}</small></span><span className={movement.quantityDelta>=0?'positive':'negative'}>{movement.quantityDelta>=0?'+':''}{movement.quantityDelta}</span></div>)}</div></article>
 </section><MobileNav/></main>;
}
