export const PERMISSION_CATALOG = [
  ['products.read', 'products', 'Ver productos'],
  ['products.create', 'products', 'Crear productos'],
  ['products.update', 'products', 'Modificar productos'],
  ['products.archive', 'products', 'Archivar productos'],
  ['costs.read', 'pricing', 'Ver costos'],
  ['profits.read', 'pricing', 'Ver ganancias'],
  ['prices.update', 'pricing', 'Modificar precios'],
  ['inventory.read', 'inventory', 'Ver stock'],
  ['inventory.adjust', 'inventory', 'Ajustar stock'],
  ['inventory.view_history', 'inventory', 'Ver historial de stock'],
  ['sales.read', 'sales', 'Ver ventas'],
  ['sales.create', 'sales', 'Registrar ventas'],
  ['sales.void', 'sales', 'Anular ventas'],
  ['returns.create', 'sales', 'Registrar devoluciones'],
  ['customers.read', 'customers', 'Ver clientes'],
  ['customers.manage', 'customers', 'Gestionar clientes'],
  ['suppliers.manage', 'suppliers', 'Gestionar proveedores'],
  ['purchases.read', 'purchases', 'Ver compras'],
  ['purchases.manage', 'purchases', 'Gestionar compras'],
  ['reports.read', 'reports', 'Ver reportes'],
  ['exports.create', 'reports', 'Exportar información'],
  ['imports.create', 'imports', 'Importar información'],
  ['users.read', 'iam', 'Ver usuarios'],
  ['users.manage', 'iam', 'Gestionar usuarios'],
  ['roles.manage', 'iam', 'Gestionar roles y permisos'],
  ['audit.read', 'audit', 'Ver auditoría'],
  ['settings.manage', 'settings', 'Gestionar configuración'],
  ['backups.manage', 'backups', 'Gestionar backups'],
] as const;
