'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { SessionUser } from '@crm/contracts';
import { api } from '../../lib/api';
import { AppNav } from '../components/app-nav';
import { MobileNav } from '../components/mobile-nav';

interface Variant { id:string; sku:string; barcode:string|null; salePriceAmount:string; product:{name:string}; color:{name:string}|null; size:{name:string}|null; inventory:{quantity:number;reservedQuantity:number}|null }
interface CartLine extends Variant { quantity:number }
interface PaymentMethod { id:string; name:string }
interface Customer { id:string; firstName:string; lastName:string|null }
interface Sale { id:string; number:string; status:string; totalAmount:string; confirmedAt:string; customer:Customer|null; items:Array<{id:string;productName:string;sku:string;quantity:number}>; payments:Array<{amount:string;paymentMethod:{name:string}}> }

const ars = new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'});
export default function SalesPage(){
  const router=useRouter(); const [me,setMe]=useState<SessionUser|null>(null); const [query,setQuery]=useState(''); const [results,setResults]=useState<Variant[]>([]); const [cart,setCart]=useState<CartLine[]>([]); const [methods,setMethods]=useState<PaymentMethod[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [sales,setSales]=useState<Sale[]>([]); const [customerId,setCustomerId]=useState(''); const [discount,setDiscount]=useState('0'); const [payments,setPayments]=useState<Array<{paymentMethodId:string;amount:string}>>([]); const [feedback,setFeedback]=useState<{error?:string;message?:string}>({});
  const load=useCallback(async()=>{try{const [session,paymentRows,customerRows,saleRows]=await Promise.all([api<SessionUser>('/auth/me'),api<PaymentMethod[]>('/payment-methods'),api<{data:Customer[]}>('/customers?pageSize=100'),api<{data:Sale[]}>('/sales?pageSize=12')]);if(!session.permissions.includes('sales.create'))return router.replace('/dashboard');setMe(session);setMethods(paymentRows);setCustomers(customerRows.data);setSales(saleRows.data);setPayments((current)=>current.length?current:paymentRows[0]?[{paymentMethodId:paymentRows[0].id,amount:''}]:[]);}catch{router.replace('/login');}},[router]); useEffect(()=>{void load();},[load]);
  const subtotal=useMemo(()=>cart.reduce((sum,line)=>sum+Number(line.salePriceAmount)*line.quantity,0),[cart]); const total=Math.max(0,subtotal-Number(discount||0));
  async function search(event:FormEvent){event.preventDefault();setFeedback({});if(!query.trim())return;try{setResults(await api<Variant[]>(`/sales/catalog?search=${encodeURIComponent(query.trim())}`));}catch(cause){setFeedback({error:cause instanceof Error?cause.message:'No se pudo buscar.'});}}
  function add(item:Variant){const available=(item.inventory?.quantity??0)-(item.inventory?.reservedQuantity??0);if(available<1)return setFeedback({error:'Producto sin stock suficiente.'});setCart((rows)=>{const current=rows.find((row)=>row.id===item.id);return current?rows.map((row)=>row.id===item.id?{...row,quantity:Math.min(available,row.quantity+1)}:row):[...rows,{...item,quantity:1}];});setQuery('');setResults([]);}
  function quantity(id:string,value:number){setCart((rows)=>rows.map((row)=>row.id===id?{...row,quantity:Math.max(1,Math.min((row.inventory?.quantity??0)-(row.inventory?.reservedQuantity??0),value))}:row));}
  async function confirm(){setFeedback({});if(!cart.length)return setFeedback({error:'Agregá al menos un producto.'});const paid=payments.reduce((sum,p)=>sum+Number(p.amount||0),0);if(Math.abs(paid-total)>.005)return setFeedback({error:`Los pagos deben sumar ${ars.format(total)}.`});try{const sale=await api<Sale>('/sales',{method:'POST',body:JSON.stringify({idempotencyKey:crypto.randomUUID(),customerId:customerId||undefined,items:cart.map((line)=>({variantId:line.id,quantity:line.quantity})),discountAmount:Number(discount||0).toFixed(2),payments,notes:undefined})});setCart([]);setDiscount('0');setCustomerId('');setFeedback({message:`Venta #${sale.number} confirmada por ${ars.format(Number(sale.totalAmount))}.`});await load();}catch(cause){setFeedback({error:cause instanceof Error?cause.message:'La venta no pudo completarse.'});}}
  if(!me)return <main className="loading-screen">Cargando punto de venta…</main>;
  return <main className="app-shell"><AppNav active="/sales"/><section className="workspace admin-workspace"><header><div><p className="eyebrow dark">PUNTO DE VENTA</p><h1>Nueva venta</h1><p className="muted">Buscá, cobrá y descontá stock en una sola operación segura.</p></div><span className="status"><i/> Caja conectada</span></header>{(feedback.error||feedback.message)&&<p className={feedback.error?'error':'success'}>{feedback.error||feedback.message}</p>}
  <div className="pos-layout"><section className="pos-catalog"><form className="search-bar" onSubmit={search}><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Nombre, SKU o escanear código…" autoFocus/><button>Buscar</button></form>{results.length>0&&<div className="search-results">{results.map((item)=><button key={item.id} onClick={()=>add(item)}><span><strong>{item.product.name}</strong><small>{item.sku} · {[item.color?.name,item.size?.name].filter(Boolean).join(' · ')||'Única'}</small></span><span><strong>{ars.format(Number(item.salePriceAmount))}</strong><small>{(item.inventory?.quantity??0)-(item.inventory?.reservedQuantity??0)} disponibles</small></span></button>)}</div>}
  <section className="table-card cart-card"><div className="table-title"><h2>Carrito</h2><span>{cart.reduce((sum,row)=>sum+row.quantity,0)} unidades</span></div>{cart.length===0?<p className="muted">Escaneá o buscá un producto para comenzar.</p>:<div className="cart-lines">{cart.map((line)=><article key={line.id}><div><strong>{line.product.name}</strong><small>{line.sku}</small></div><input aria-label={`Cantidad ${line.sku}`} type="number" min={1} value={line.quantity} onChange={(e)=>quantity(line.id,Number(e.target.value))}/><strong>{ars.format(Number(line.salePriceAmount)*line.quantity)}</strong><button className="secondary" onClick={()=>setCart((rows)=>rows.filter((row)=>row.id!==line.id))}>Quitar</button></article>)}</div>}</section></section>
  <aside className="checkout-card admin-card"><h2>Cobro</h2><label>Cliente<select value={customerId} onChange={(e)=>setCustomerId(e.target.value)}><option value="">Consumidor final</option>{customers.map((customer)=><option key={customer.id} value={customer.id}>{customer.firstName} {customer.lastName}</option>)}</select></label><label>Descuento total<input type="number" min="0" step="0.01" value={discount} onChange={(e)=>setDiscount(e.target.value)}/></label><div className="checkout-totals"><span>Subtotal<strong>{ars.format(subtotal)}</strong></span><span>Total<strong>{ars.format(total)}</strong></span></div><h3>Pagos</h3>{payments.map((payment,index)=><div className="payment-row" key={index}><select value={payment.paymentMethodId} onChange={(e)=>setPayments((rows)=>rows.map((row,i)=>i===index?{...row,paymentMethodId:e.target.value}:row))}>{methods.map((method)=><option key={method.id} value={method.id}>{method.name}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Importe" value={payment.amount} onChange={(e)=>setPayments((rows)=>rows.map((row,i)=>i===index?{...row,amount:e.target.value}:row))}/>{payments.length>1&&<button className="secondary" onClick={()=>setPayments((rows)=>rows.filter((_,i)=>i!==index))}>×</button>}</div>)}<button className="secondary" onClick={()=>methods[0]&&setPayments((rows)=>[...rows,{paymentMethodId:methods[0].id,amount:''}])}>+ Pago combinado</button><button className="confirm-sale" onClick={()=>void confirm()} disabled={!cart.length}>Confirmar venta</button></aside></div>
  <section className="table-card recent-sales"><div className="table-title"><h2>Últimas ventas</h2><span>{sales.length} recientes</span></div><div className="responsive-table"><table><thead><tr><th>Número</th><th>Cliente</th><th>Productos</th><th>Pagos</th><th>Total</th><th>Estado</th><th/></tr></thead><tbody>{sales.map((sale)=><tr key={sale.id}><td><strong>#{sale.number}</strong><small>{new Date(sale.confirmedAt).toLocaleString('es-AR')}</small></td><td>{sale.customer?`${sale.customer.firstName} ${sale.customer.lastName??''}`:'Consumidor final'}</td><td>{sale.items.reduce((sum,item)=>sum+item.quantity,0)}</td><td>{sale.payments.map((payment)=>payment.paymentMethod.name).join(' + ')}</td><td><strong>{ars.format(Number(sale.totalAmount))}</strong></td><td><span className={`badge ${sale.status==='CONFIRMED'?'active':''}`}>{sale.status}</span></td><td><a className="secondary" href={`/sales/${sale.id}/receipt`} target="_blank">Ticket</a></td></tr>)}</tbody></table></div></section>
  </section><MobileNav/></main>;
}
