[package]
name = "crm-local-de-ropa"
version = "0.1.0"
description = "Aplicación de escritorio de Caracola"
authors = ["Caracola"]
edition = "2021"

[lib]
name = "crm_local_de_ropa_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
