'use client';
import { FormEvent,useEffect,useState } from 'react';import { useRouter } from 'next/navigation';import { api,API_URL } from '../../lib/api';import { AppNav } from '../components/app-nav';import { MobileNav } from '../components/mobile-nav';
type Row={rowNumber:number;name:string;sku:string;barcode?:string;category?:string;brand?:string;color?:string;size?:string;stock:number;cost:string;price:string};type Preview={id:string;filename:string;totalRows:number;validRows:number;errorRows:number;canConfirm:boolean;rows:Row[];errors:Array<{rowNumber:number;field:string;message:string}>;expiresAt:string};
export default function ImportsPage(){const router=useRouter();const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<Preview|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');useEffect(()=>{api('/auth/me').catch(()=>router.replace('/login'));},[router]);
 async function upload(event:FormEvent){event.preventDefault();if(!file)return;setBusy(true);setError('');setSuccess('');try{const body=new FormData();body.append('file',file);const response=await fetch(`${API_URL}/imports/products/preview`,{method:'POST',credentials:'include',body});const result=await response.json();if(!response.ok)throw new Error(result.message??'No se pudo analizar el archivo.');setPreview(result);}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo analizar el archivo.');}finally{setBusy(false);}}
 async function confirm(){if(!preview)return;setBusy(true);setError('');try{const result=await api<{createdProducts:number;createdVariants:number}>('/imports/products/confirm',{method:'POST',body:JSON.stringify({importId:preview.id})});setSuccess(`Importación completada: ${result.createdProducts} productos y ${result.createdVariants} variantes.`);setPreview(null);setFile(null);}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo confirmar.');}finally{setBusy(false);}}
 return <main className="app-shell"><AppNav active="/imports"/><section className="workspace"><header><div><p className="eyebrow dark">CARGA MASIVA SEGURA</p><h1>Importar productos</h1><p className="muted">El sistema previsualiza, valida duplicados y no guarda nada hasta tu confirmación.</p></div><a className="download-template" href={`${API_URL}/imports/products/template`}>Descargar plantilla CSV</a></header>
  <form className="import-drop table-card" onSubmit={upload}><div><strong>Seleccioná un CSV o Excel (.xlsx)</strong><p>Máximo 5 MB o 5.000 filas. Columnas obligatorias: nombre, SKU, costo y precio.</p></div><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event)=>{setFile(event.target.files?.[0]??null);setPreview(null);}}/><button disabled={!file||busy}>{busy?'Analizando…':'Previsualizar y validar'}</button></form>{error&&<p className="error">{error}</p>}{success&&<p className="success">{success}</p>}
  {preview&&<><section className="metric-grid import-metrics"><article><span>Filas encontradas</span><strong>{preview.totalRows}</strong><small>{preview.filename}</small></article><article><span>Válidas</span><strong>{preview.validRows}</strong><small>Listas para importar</small></article><article className={preview.errorRows?'metric-alert':''}><span>Con errores</span><strong>{preview.errorRows}</strong><small>Deben corregirse en el archivo</small></article><article><span>Estado</span><strong>{preview.canConfirm?'Listo':'Revisar'}</strong><small>La vista previa vence en 24 h</small></article></section>
   {preview.errors.length>0&&<article className="table-card error-list"><div className="table-title"><h2>Errores detectados</h2><span>{preview.errorRows} filas afectadas</span></div>{preview.errors.map((item,index)=><p key={`${item.rowNumber}-${item.field}-${index}`}><b>Fila {item.rowNumber} · {item.field}</b><span>{item.message}</span></p>)}</article>}
   <article className="table-card"><div className="table-title"><h2>Previsualización</h2><span>Primeras {preview.rows.length} filas</span></div><div className="responsive-table"><table><thead><tr><th>Fila</th><th>Producto</th><th>SKU</th><th>Variante</th><th>Stock</th><th>Costo</th><th>Precio</th></tr></thead><tbody>{preview.rows.map((row)=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.name}<small>{[row.category,row.brand].filter(Boolean).join(' · ')}</small></td><td>{row.sku}<small>{row.barcode}</small></td><td>{[row.color,row.size].filter(Boolean).join(' · ')||'Sin variante'}</td><td>{row.stock}</td><td>{row.cost}</td><td>{row.price}</td></tr>)}</tbody></table></div>{preview.canConfirm&&<button className="confirm-import" onClick={confirm} disabled={busy}>{busy?'Importando…':'Confirmar importación'}</button>}</article></>}
 </section><MobileNav/></main>}
