'use client';
import { useEffect,useState } from 'react';import { useRouter } from 'next/navigation';import { api,API_URL } from '../../lib/api';import { AppNav } from '../components/app-nav';import { MobileNav } from '../components/mobile-nav';
type Summary={range:{from:string;to:string};totals:{sales:number;revenue:string;purchases:number;purchaseTotal:string;profit?:string;marginPercent?:string};byPaymentMethod:Array<{name:string;amount:string;operations:number}>;byUser:Array<{name:string;amount:string;operations:number}>;products:Array<{name:string;sku:string;units:number;revenue:string;profit:string}>};
const cash=(value?:string)=>value==null?'Oculto':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(Number(value));const iso=(date:Date)=>date.toISOString().slice(0,10);
export default function ReportsPage(){const router=useRouter();const[from,setFrom]=useState(iso(new Date(Date.now()-29*86400000)));const[to,setTo]=useState(iso(new Date()));const[data,setData]=useState<Summary|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState('');
 const load=()=>{setError('');api<Summary>(`/reports/summary?from=${from}&to=${to}`).then(setData).catch((reason)=>setError(reason instanceof Error?reason.message:'No se pudo generar el reporte.'));};useEffect(()=>{api('/auth/me').then(load).catch(()=>router.replace('/login'));},[router]);
 async function download(dataset:string,format:string){setBusy(`${dataset}-${format}`);setError('');try{const response=await fetch(`${API_URL}/reports/export?dataset=${dataset}&format=${format}&from=${from}&to=${to}`,{credentials:'include'});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message??'No se pudo exportar.');const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${dataset}-${to}.${format}`;anchor.click();URL.revokeObjectURL(url);}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo exportar.');}finally{setBusy('');}}
 return <main className="app-shell"><AppNav active="/reports"/><section className="workspace"><header><div><p className="eyebrow dark">ANÁLISIS COMERCIAL</p><h1>Reportes</h1><p className="muted">Ventas, rentabilidad, medios de pago, productos e inventario.</p></div></header><section className="report-toolbar table-card"><label>Desde<input type="date" value={from} onChange={(event)=>setFrom(event.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={(event)=>setTo(event.target.value)}/></label><button onClick={load}>Actualizar reporte</button></section>{error&&<p className="error">{error}</p>}
  {data&&<><section className="metric-grid report-metrics"><article><span>Ventas netas</span><strong>{cash(data.totals.revenue)}</strong><small>{data.totals.sales} operaciones</small></article><article><span>Ganancia</span><strong>{cash(data.totals.profit)}</strong><small>{data.totals.marginPercent?`${data.totals.marginPercent}% de margen`:'Según permisos'}</small></article><article><span>Compras</span><strong>{cash(data.totals.purchaseTotal)}</strong><small>{data.totals.purchases} ingresos</small></article><article><span>Ticket promedio</span><strong>{cash(data.totals.sales?String(Number(data.totals.revenue)/data.totals.sales):'0')}</strong><small>Venta neta promedio</small></article></section>
  <section className="export-center table-card"><div><h2>Exportar información</h2><p className="muted">Descargas compatibles con Excel, archivos CSV y documentos PDF listos para imprimir.</p></div>{['stock','sales','purchases','audit'].map((dataset)=><div className="export-row" key={dataset}><strong>{({stock:'Stock completo',sales:'Ventas',purchases:'Compras',audit:'Auditoría'} as Record<string,string>)[dataset]}</strong>{['csv','xlsx','pdf'].map((format)=><button disabled={!!busy} onClick={()=>download(dataset,format)} key={format}>{busy===`${dataset}-${format}`?'Generando…':format.toUpperCase()}</button>)}</div>)}</section>
  <section className="dashboard-grid lower"><article className="table-card"><div className="table-title"><h2>Por método de pago</h2><span>{data.byPaymentMethod.length} métodos</span></div><div className="rank-list">{data.byPaymentMethod.map((item,index)=><div key={item.name}><b>{index+1}</b><span><strong>{item.name}</strong><small>{item.operations} ventas</small></span><strong>{cash(item.amount)}</strong></div>)}</div></article><article className="table-card"><div className="table-title"><h2>Por vendedor</h2><span>Rendimiento</span></div><div className="rank-list">{data.byUser.map((item,index)=><div key={item.name}><b>{index+1}</b><span><strong>{item.name}</strong><small>{item.operations} ventas</small></span><strong>{cash(item.amount)}</strong></div>)}</div></article></section>
  <article className="table-card"><div className="table-title"><h2>Productos más vendidos</h2><span>Unidades netas del período</span></div><div className="responsive-table"><table><thead><tr><th>Producto</th><th>SKU</th><th>Unidades</th><th>Ingresos</th><th>Ganancia</th></tr></thead><tbody>{data.products.map((item)=><tr key={item.sku}><td>{item.name}</td><td>{item.sku}</td><td>{item.units}</td><td>{cash(item.revenue)}</td><td>{cash(item.profit)}</td></tr>)}</tbody></table></div></article></>}
 </section><MobileNav/></main>}
