'use client';
import { useEffect,useState } from 'react';import { useRouter } from 'next/navigation';import { api } from '../../lib/api';import { AppNav } from '../components/app-nav';import { MobileNav } from '../components/mobile-nav';
type Audit={id:string;action:string;entityType:string;entityId?:string;beforeData?:unknown;afterData?:unknown;ip?:string;requestId?:string;occurredAt:string;actor?:{displayName:string;username:string}};type Result={data:Audit[];pagination:{page:number;pages:number;total:number}};
const labels:Record<string,string>={'sale.confirmed':'Venta confirmada','sale.voided':'Venta anulada','purchase.confirmed':'Compra confirmada','return.confirmed':'Devolución o cambio','product.created':'Producto creado','product.updated':'Producto modificado','inventory.adjusted':'Stock ajustado','import.products.confirmed':'Importación confirmada','report.exported':'Reporte exportado','auth.login.succeeded':'Inicio de sesión'};
export default function AuditPage(){const router=useRouter();const[data,setData]=useState<Result|null>(null);const[search,setSearch]=useState('');const[action,setAction]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState('');const[page,setPage]=useState(1);const[error,setError]=useState('');
 const load=(nextPage=page)=>{const params=new URLSearchParams({page:String(nextPage),pageSize:'30'});if(search)params.set('search',search);if(action)params.set('action',action);if(from)params.set('from',from);if(to)params.set('to',to);api<Result>(`/audit?${params}`).then(setData).catch((reason)=>setError(reason instanceof Error?reason.message:'No se pudo cargar la auditoría.'));};useEffect(()=>{api('/auth/me').then(()=>load(1)).catch(()=>router.replace('/login'));},[router]);
 function filter(){setPage(1);load(1);}return <main className="app-shell"><AppNav active="/audit"/><section className="workspace"><header><div><p className="eyebrow dark">TRAZABILIDAD</p><h1>Auditoría</h1><p className="muted">Quién hizo qué, cuándo y sobre qué registro.</p></div>{data&&<div className="status">{data.pagination.total.toLocaleString('es-AR')} eventos</div>}</header>
  <section className="audit-filters table-card"><input placeholder="Buscar acción, entidad, usuario o ID" value={search} onChange={(event)=>setSearch(event.target.value)}/><select value={action} onChange={(event)=>setAction(event.target.value)}><option value="">Todas las acciones</option><option value="sale.">Ventas</option><option value="purchase.">Compras</option><option value="return.">Devoluciones</option><option value="product.">Productos</option><option value="inventory.">Inventario</option><option value="import.">Importaciones</option><option value="report.">Exportaciones</option><option value="auth.">Accesos</option></select><input type="date" value={from} onChange={(event)=>setFrom(event.target.value)}/><input type="date" value={to} onChange={(event)=>setTo(event.target.value)}/><button onClick={filter}>Filtrar</button></section>{error&&<p className="error">{error}</p>}
  <article className="table-card audit-list">{data?.data.map((item)=><details key={item.id}><summary><span className="audit-icon">{item.action.split('.')[0].slice(0,2).toUpperCase()}</span><span><strong>{labels[item.action]??item.action}</strong><small>{item.actor?.displayName??'Sistema'} · {item.entityType}{item.entityId?` #${item.entityId.slice(0,8)}`:''}</small></span><time>{new Date(item.occurredAt).toLocaleString('es-AR')}</time></summary><div className="audit-detail"><dl><div><dt>Usuario</dt><dd>{item.actor?`${item.actor.displayName} (${item.actor.username})`:'Sistema'}</dd></div><div><dt>Entidad</dt><dd>{item.entityType} · {item.entityId??'Sin ID'}</dd></div><div><dt>IP</dt><dd>{item.ip??'No registrada'}</dd></div><div><dt>Solicitud</dt><dd>{item.requestId??'No registrada'}</dd></div></dl>{item.beforeData!=null&&<div><h3>Antes</h3><pre>{JSON.stringify(item.beforeData,null,2)}</pre></div>}{item.afterData!=null&&<div><h3>Después</h3><pre>{JSON.stringify(item.afterData,null,2)}</pre></div>}</div></details>)}</article>
  {data&&data.pagination.pages>1&&<div className="pagination"><button disabled={page<=1} onClick={()=>{const next=page-1;setPage(next);load(next);}}>Anterior</button><span>Página {page} de {data.pagination.pages}</span><button disabled={page>=data.pagination.pages} onClick={()=>{const next=page+1;setPage(next);load(next);}}>Siguiente</button></div>}
 </section><MobileNav/></main>}
