import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { ActionContext } from '../iam/users.service';
import { PrismaService } from '../prisma/prisma.service';
import { money, moneyText, sumMoney } from '../common/money';
import { RealtimeService } from '../realtime/realtime.service';
import { CreatePurchaseDto, PurchaseQueryDto } from './purchase.dto';

const include = { supplier: true, user: { select: { id: true, displayName: true } }, items: true, payments: { include: { paymentMethod: true } } } as const;
@Injectable()
export class PurchasesService {
  constructor(private readonly prisma: PrismaService, private readonly realtime: RealtimeService) {}
  catalog(search: string) { return this.prisma.productVariant.findMany({ where: { archivedAt: null, product: { archivedAt: null }, OR: [{ sku: { contains: search, mode: 'insensitive' } }, { barcode: { equals: search } }, { product: { name: { contains: search, mode: 'insensitive' } } }] }, take: 30, orderBy: { sku: 'asc' }, select: { id: true, sku: true, costAmount: true, product: { select: { name: true } }, inventory: { select: { quantity: true } } } }); }
  async list(query: PurchaseQueryDto) { const where = query.supplierId ? { supplierId: query.supplierId } : {}; const [total, rows] = await this.prisma.$transaction([this.prisma.supplierPurchase.count({ where }), this.prisma.supplierPurchase.findMany({ where, skip: (query.page - 1) * query.pageSize, take: query.pageSize, orderBy: { confirmedAt: 'desc' }, include })]); return { data: rows.map((row) => this.serialize(row)), pagination: { page: query.page, pageSize: query.pageSize, total, pages: Math.ceil(total / query.pageSize) } }; }
  async get(id: string) { const purchase = await this.prisma.supplierPurchase.findUnique({ where: { id }, include }); if (!purchase) throw new NotFoundException('La compra no existe.'); return this.serialize(purchase); }
  async create(input: CreatePurchaseDto, context: ActionContext) {
    const previous = await this.prisma.supplierPurchase.findUnique({ where: { idempotencyKey: input.idempotencyKey }, include }); if (previous) return this.serialize(previous);
    const grouped = new Map<string, { quantity: number; unitCost: Prisma.Decimal }>(); for (const item of input.items) { const cost = money(item.unitCostAmount, 'costo'); const current = grouped.get(item.variantId); if (current && !current.unitCost.equals(cost)) throw new BadRequestException('Una variante no puede repetirse con costos distintos.'); grouped.set(item.variantId, { quantity: (current?.quantity ?? 0) + item.quantity, unitCost: cost }); }
    try {
      const purchase = await this.prisma.$transaction(async (tx) => {
        if (!await tx.supplier.findFirst({ where: { id: input.supplierId, archivedAt: null } })) throw new NotFoundException('El proveedor no existe.');
        const ids = [...grouped.keys()].sort(); const variants = await tx.productVariant.findMany({ where: { id: { in: ids }, archivedAt: null }, include: { product: { select: { id: true, name: true } } } }); if (variants.length !== ids.length) throw new NotFoundException('Una variante no existe.'); const byId = new Map(variants.map((variant) => [variant.id, variant]));
        const balances = new Map<string, number>(); for (const id of ids) { const rows = await tx.$queryRaw<Array<{ quantity: number }>>`SELECT quantity FROM inventory_balances WHERE variant_id = ${id}::uuid FOR UPDATE`; if (!rows[0]) throw new NotFoundException('Una variante no tiene saldo de inventario.'); balances.set(id, rows[0].quantity); }
        const lines = [...grouped].map(([variantId, item]) => ({ variant: byId.get(variantId)!, ...item, total: item.unitCost.mul(item.quantity) })); const total = sumMoney(lines.map((line) => line.total)); const paid = sumMoney(input.payments.map((payment) => money(payment.amount, 'pago'))); if (!paid.equals(total)) throw new BadRequestException(`Los pagos deben sumar exactamente ${moneyText(total)}.`);
        const methodIds = [...new Set(input.payments.map((payment) => payment.paymentMethodId))]; if (await tx.paymentMethod.count({ where: { id: { in: methodIds }, isActive: true } }) !== methodIds.length) throw new BadRequestException('Uno de los métodos de pago no está disponible.');
        const created = await tx.supplierPurchase.create({ data: { idempotencyKey: input.idempotencyKey.trim(), supplierId: input.supplierId, userId: context.actor.id, totalAmount: total, notes: input.notes?.trim(), items: { create: lines.map((line) => ({ variantId: line.variant.id, productName: line.variant.product.name, sku: line.variant.sku, quantity: line.quantity, unitCostAmount: line.unitCost, lineTotalAmount: line.total })) }, payments: { create: input.payments.map((payment) => ({ paymentMethodId: payment.paymentMethodId, amount: money(payment.amount, 'pago'), reference: payment.reference?.trim() })) } }, include });
        for (const line of lines) { const before = balances.get(line.variant.id)!; const after = before + line.quantity; await tx.inventoryBalance.update({ where: { variantId: line.variant.id }, data: { quantity: after, version: { increment: 1 } } }); await tx.inventoryMovement.create({ data: { variantId: line.variant.id, type: 'PURCHASE', quantityDelta: line.quantity, quantityBefore: before, quantityAfter: after, reasonCode: 'supplier_purchase', referenceType: 'supplier_purchase', referenceId: created.id, userId: context.actor.id } }); if (!line.variant.costAmount.equals(line.unitCost)) { await tx.priceHistory.create({ data: { variantId: line.variant.id, priceType: 'COST', oldAmount: line.variant.costAmount, newAmount: line.unitCost, reason: `Compra #${created.number.toString()}`, changedBy: context.actor.id } }); await tx.productVariant.update({ where: { id: line.variant.id }, data: { costAmount: line.unitCost } }); } await tx.productSupplier.upsert({ where: { productId_supplierId_variantId: { productId: line.variant.product.id, supplierId: input.supplierId, variantId: line.variant.id } }, update: { lastCostAmount: line.unitCost }, create: { productId: line.variant.product.id, supplierId: input.supplierId, variantId: line.variant.id, lastCostAmount: line.unitCost } }); }
        await tx.auditLog.create({ data: { actorUserId: context.actor.id, action: 'purchase.confirmed', entityType: 'supplier_purchase', entityId: created.id, afterData: { number: created.number.toString(), total: moneyText(total), supplierId: input.supplierId }, ip: context.ip, userAgent: context.userAgent?.slice(0, 512), requestId: context.requestId } }); return created;
      }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, maxWait: 5000, timeout: 15000 });
      this.realtime.publish('purchase.confirmed', { purchaseId: purchase.id, number: purchase.number.toString() }); return this.serialize(purchase);
    } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') { const duplicate = await this.prisma.supplierPurchase.findUnique({ where: { idempotencyKey: input.idempotencyKey }, include }); if (duplicate) return this.serialize(duplicate); } throw error; }
  }
  private serialize<T extends { number: bigint; totalAmount: Prisma.Decimal }>(purchase: T) { return { ...purchase, number: purchase.number.toString(), totalAmount: moneyText(purchase.totalAmount) }; }
}
