import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { ActionContext } from '../iam/users.service';
import { PrismaService } from '../prisma/prisma.service';
import { money, moneyText, sumMoney } from '../common/money';
import { RealtimeService } from '../realtime/realtime.service';
import { jsonSafe } from '../common/json-safe';
import { CreateReturnDto } from './return.dto';

const include = { sale: { select: { id: true, number: true } }, user: { select: { id: true, displayName: true } }, items: true, exchangeItems: true, settlements: { include: { paymentMethod: true } } } as const;
@Injectable()
export class ReturnsService {
  constructor(private readonly prisma: PrismaService, private readonly realtime: RealtimeService) {}
  async list(saleId?: string) { const rows = await this.prisma.returnTransaction.findMany({ where: saleId ? { saleId } : {}, take: 100, orderBy: { confirmedAt: 'desc' }, include }); return rows.map((row) => this.serialize(row)); }
  async create(input: CreateReturnDto, context: ActionContext) {
    const previous = await this.prisma.returnTransaction.findUnique({ where: { idempotencyKey: input.idempotencyKey }, include }); if (previous) return this.serialize(previous);
    if (input.type === 'RETURN' && input.exchangeItems?.length) throw new BadRequestException('Una devolución no puede incluir productos de cambio.'); if (input.type === 'EXCHANGE' && !input.exchangeItems?.length) throw new BadRequestException('El cambio debe incluir al menos un producto de reemplazo.');
    const requested = new Map<string, number>(); for (const item of input.items) requested.set(item.saleItemId, (requested.get(item.saleItemId) ?? 0) + item.quantity);
    const replacements = new Map<string, number>(); for (const item of input.exchangeItems ?? []) replacements.set(item.variantId, (replacements.get(item.variantId) ?? 0) + item.quantity);
    try {
      const result = await this.prisma.$transaction(async (tx) => {
        const sale = await tx.sale.findUnique({ where: { id: input.saleId }, include: { items: true } }); if (!sale) throw new NotFoundException('La venta no existe.'); if (sale.status === 'VOIDED') throw new BadRequestException('La venta está anulada.');
        const saleItems = new Map(sale.items.map((item) => [item.id, item])); for (const [itemId, quantity] of requested) { const item = saleItems.get(itemId); if (!item) throw new BadRequestException('Un producto no pertenece a la venta.'); if (item.returnedQuantity + quantity > item.quantity) throw new BadRequestException(`La devolución supera la cantidad vendida de ${item.sku}.`); }
        const replacementIds = [...replacements.keys()]; const variants = replacementIds.length ? await tx.productVariant.findMany({ where: { id: { in: replacementIds }, archivedAt: null, status: 'ACTIVE', product: { archivedAt: null, status: 'ACTIVE' } }, include: { product: { select: { name: true } } } }) : []; if (variants.length !== replacementIds.length) throw new NotFoundException('Un producto de reemplazo no está disponible.'); const variantMap = new Map(variants.map((variant) => [variant.id, variant]));
        const allVariantIds = [...new Set([...sale.items.filter((item) => requested.has(item.id)).map((item) => item.variantId), ...replacementIds])].sort(); const balances = new Map<string, number>(); for (const variantId of allVariantIds) { const rows = await tx.$queryRaw<Array<{ quantity: number }>>`SELECT quantity FROM inventory_balances WHERE variant_id = ${variantId}::uuid FOR UPDATE`; if (!rows[0]) throw new NotFoundException('No existe un saldo de inventario.'); balances.set(variantId, rows[0].quantity); }
        const returnedByVariant = new Map<string, number>(); const returnLines = [...requested].map(([saleItemId, quantity]) => { const item = saleItems.get(saleItemId)!; returnedByVariant.set(item.variantId, (returnedByVariant.get(item.variantId) ?? 0) + quantity); const unitRefund = item.lineTotalAmount.div(item.quantity); return { item, quantity, unitRefund, refund: unitRefund.mul(quantity) }; }); const refund = sumMoney(returnLines.map((line) => line.refund));
        const exchangeLines = [...replacements].map(([variantId, quantity]) => { const variant = variantMap.get(variantId)!; return { variant, quantity, total: variant.salePriceAmount.mul(quantity) }; }); const replacementTotal = sumMoney(exchangeLines.map((line) => line.total)); const difference = replacementTotal.minus(refund);
        for (const line of exchangeLines) { const available = balances.get(line.variant.id)! + (returnedByVariant.get(line.variant.id) ?? 0); if (available < line.quantity) throw new ConflictException(`Stock insuficiente para ${line.variant.sku}.`); }
        const settlements = input.settlements ?? []; const expectedType = difference.isPositive() ? 'COLLECTION' : difference.isNegative() ? 'REFUND' : null; if (expectedType) { if (settlements.some((settlement) => settlement.type !== expectedType)) throw new BadRequestException(`La diferencia requiere una ${expectedType === 'COLLECTION' ? 'cobranza' : 'devolución'} de dinero.`); const amount = sumMoney(settlements.map((settlement) => money(settlement.amount, 'importe'))); if (!amount.equals(difference.abs())) throw new BadRequestException(`Las liquidaciones deben sumar exactamente ${moneyText(difference.abs())}.`); } else if (settlements.length) throw new BadRequestException('No corresponde registrar una liquidación cuando la diferencia es cero.');
        const methodIds = [...new Set(settlements.map((settlement) => settlement.paymentMethodId))]; if (methodIds.length && await tx.paymentMethod.count({ where: { id: { in: methodIds }, isActive: true } }) !== methodIds.length) throw new BadRequestException('Un método de pago no está disponible.');
        const created = await tx.returnTransaction.create({ data: { idempotencyKey: input.idempotencyKey.trim(), saleId: sale.id, userId: context.actor.id, type: input.type, refundAmount: refund, replacementAmount: replacementTotal, differenceAmount: difference, reason: input.reason.trim(), notes: input.notes?.trim(), items: { create: returnLines.map((line) => ({ saleItemId: line.item.id, variantId: line.item.variantId, quantity: line.quantity, unitPriceAmount: line.unitRefund, refundAmount: line.refund })) }, exchangeItems: { create: exchangeLines.map((line) => ({ variantId: line.variant.id, productName: line.variant.product.name, sku: line.variant.sku, quantity: line.quantity, unitPriceAmount: line.variant.salePriceAmount, lineTotalAmount: line.total })) }, settlements: { create: settlements.map((settlement) => ({ paymentMethodId: settlement.paymentMethodId, type: settlement.type, amount: money(settlement.amount, 'importe'), reference: settlement.reference?.trim() })) } }, include });
        for (const line of returnLines) await tx.saleItem.update({ where: { id: line.item.id }, data: { returnedQuantity: { increment: line.quantity } } });
        for (const variantId of allVariantIds) { const before = balances.get(variantId)!; const incoming = returnedByVariant.get(variantId) ?? 0; const outgoing = replacements.get(variantId) ?? 0; const afterReturn = before + incoming; if (incoming) await tx.inventoryMovement.create({ data: { variantId, type: input.type === 'EXCHANGE' ? 'EXCHANGE_IN' : 'RETURN', quantityDelta: incoming, quantityBefore: before, quantityAfter: afterReturn, reasonCode: input.type.toLowerCase(), notes: input.reason.trim(), referenceType: 'return', referenceId: created.id, userId: context.actor.id } }); const after = afterReturn - outgoing; if (outgoing) await tx.inventoryMovement.create({ data: { variantId, type: 'EXCHANGE_OUT', quantityDelta: -outgoing, quantityBefore: afterReturn, quantityAfter: after, reasonCode: 'exchange', notes: input.reason.trim(), referenceType: 'return', referenceId: created.id, userId: context.actor.id } }); await tx.inventoryBalance.update({ where: { variantId }, data: { quantity: after, version: { increment: 1 } } }); }
        const totalReturned = sale.items.reduce((sum, item) => sum + item.returnedQuantity + (requested.get(item.id) ?? 0), 0); const totalSold = sale.items.reduce((sum, item) => sum + item.quantity, 0); await tx.sale.update({ where: { id: sale.id }, data: { status: totalReturned === totalSold ? 'RETURNED' : 'PARTIALLY_RETURNED' } }); await tx.auditLog.create({ data: { actorUserId: context.actor.id, action: input.type === 'EXCHANGE' ? 'sale.exchanged' : 'sale.returned', entityType: 'return_transaction', entityId: created.id, afterData: { saleId: sale.id, refund: moneyText(refund), replacement: moneyText(replacementTotal), difference: moneyText(difference.abs()) }, ip: context.ip, userAgent: context.userAgent?.slice(0, 512), requestId: context.requestId } }); return created;
      }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, maxWait: 5000, timeout: 15000 });
      this.realtime.publish('sale.returned', { returnId: result.id, saleId: input.saleId, type: input.type }); return this.serialize(result);
    } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') { const duplicate = await this.prisma.returnTransaction.findUnique({ where: { idempotencyKey: input.idempotencyKey }, include }); if (duplicate) return this.serialize(duplicate); } throw error; }
  }
  private serialize<T extends { number: bigint; refundAmount: Prisma.Decimal; replacementAmount: Prisma.Decimal; differenceAmount: Prisma.Decimal }>(result: T) { return jsonSafe({ ...result, number: result.number.toString(), refundAmount: moneyText(result.refundAmount), replacementAmount: moneyText(result.replacementAmount), differenceAmount: result.differenceAmount.toFixed(2) }); }
}
